version: '3'
services:
    servicemonitor:
        image: mysticrenji/servicemonitor
        volumes:
            - ./01.servicemonitor:/app
    nginx:
        restart: always
        image: mysticrenji/servicemonitor-nginx
        volumes:
            - ./01.servicemonitor/staticfiles/:/usr/share/nginx/html
        ports:
          - '80:80'